manifest:
  projects:
    - name: zephyr
      revision: e06bac0e4f2537ec1547c1c2cca80d5f25fdf0a3
      url: https://github.com/zephyrproject-rtos/zephyr
      west-commands: scripts/west-commands.yml
      import: true

  self:
    path: modules/lib/golioth
    west-commands: scripts/west-commands.yml
