manifest:
  projects:
    - name: zephyr
      revision: v2.6.0
      url: https://github.com/zephyrproject-rtos/zephyr
      west-commands: scripts/west-commands.yml
      import:
        name-allowlist:
          - cmsis
          - hal_espressif
          - hal_nordic
          - mbedtls
          - mcuboot
          - mcumgr
          - net-tools
          - segger
          - tinycbor
          - tinycrypt

  self:
    path: modules/lib/golioth
    west-commands: scripts/west-commands.yml
