manifest:
  projects:
    - name: zephyr
      revision: c1e1273df2a23329314a51023ac5f76069ecb5c4
      url: https://github.com/zephyrproject-rtos/zephyr
      west-commands: scripts/west-commands.yml
      import: true

  self:
    path: modules/lib/golioth
