manifest:
  projects:
    - name: zephyr
      revision: 9f12dbba5d84842eb7be3cf7412ee88d45267b55
      url: https://github.com/zephyrproject-rtos/zephyr
      west-commands: scripts/west-commands.yml
      import: true

  self:
    path: modules/lib/golioth
    west-commands: scripts/west-commands.yml
